# Generated by Django 2.2.4 on 2019-08-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190830_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='data_sheet',
        ),
    ]
