# Generated by Django 2.2.4 on 2019-08-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_data_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='customer',
        ),
    ]
