# Generated by Django 2.2.4 on 2019-08-30 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_document_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='data_sheet',
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
            preserve_default=False,
        ),
    ]
