# Generated by Django 2.2.4 on 2019-08-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190830_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_sheet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.DataSheet'),
            preserve_default=False,
        ),
    ]
