# Generated by Django 2.2.4 on 2019-08-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customer_data_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='professions',
        ),
    ]
